### ISSUE TITLE
Hosting Pages Not Found

### ISSUE THREAD

**Issue by Md-Dipu** [Riadul-Islam-551/first_pro#1]
Hi @Riadul-Islam-551,

As you're the owner of the repository, it's more important to host the site we have developed. Please make the pages deploy on GH Pages. 

_**Thank you**_

**Comment by Riadul-Islam-551** [comment]
Done. I think now you will get the site link.

**Comment by Md-Dipu** [comment]
Don't forget to close the issue after you done.

**Comment by Riadul-Islam-551** [comment]
how can  I close it

**Comment by Md-Dipu** [comment]
Use Close issue button.

**Comment by Riadul-Islam-551** [comment]
ok.......
make the hosting site
